/* Solution for Problem 2 found at: https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var num1 = 0;
var num2 = 1;
var num3 = 0;
var totalSum = 0;
var limit = 4000000;

for(var i=1; i<100; i++){
    
    num3 = num1 + num2;
    
    num1 = num2;
    
    num2 = num3;
    
    if((num3<=limit)&&(num3%2===0)){
        
        totalSum+=num3;
    } 
}
console.log(totalSum);